// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ProductStoreClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Product
    {
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product() { }

        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product(string productID = default(string), string name = default(string), double? price = default(double?), string category = default(string))
        {
            ProductID = productID;
            Name = name;
            Price = price;
            Category = category;
        }

        /// <summary>
        /// Product ID
        /// </summary>
        [JsonProperty(PropertyName = "ProductID")]
        public string ProductID { get; set; }

        /// <summary>
        /// Name of the product
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Price of the product
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

        /// <summary>
        /// Category of the product
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

    }
}
